version: '3'

services:
  # Selenium hub
  selenium_hub:
    image: selenium/hub
    ports:
      - 4444:4444

  # Appium Docker Android  
  appium_android_device:
    image: appium/appium
    depends_on:
      - selenium_hub
    privileged: true
    ports:
      - 4723:4723
    volumes:
      # - /dev/bus/usb:/dev/bus/usb
      - ~/.android:/root/.android
      - ${PATH_DIR_APK}:/opt
    environment:
      - REMOTE_ADB=true
      - ANDROID_DEVICES=${DEVICE_HOST}:${DEVICE_PORT}
      - REMOTE_ADB_POLLING_SEC=60
      - CHROMEDRIVER_AUTODOWNLOAD=true
      - CONNECT_TO_GRID=true
      - SELENIUM_HOST=selenium_hub
